import { Order } from './types/order';

export const ORDERS: Order[] = [
  {
    id: '1',
    item: 'Order 1',
    details: 'Details about order 1',
    status: 'Pending',
    slug: 'order-1',
    date: '2024-07-01',
    items: [
      {
        id: 1,
        title: 'Nike Air Max 2024',
        slug: 'nike-air-max-2024',
        heroImage: require('../assets/images/shoes1.png'),
        imagesUrl: [
          require('../assets/images/shoes1.png'),
          require('../assets/images/shoes2.png'),
          require('../assets/images/shoes3.png'),
        ],
        price: 199.99,
        category: {
          imageUrl: require('../assets/images/shoes1.png'),
          name: 'Nike',
          slug: 'nike',
        },
        gender: 'Unisex',
        sizes: [7, 8, 9, 10, 11],
        maxQuantity: 5,
      },
      {
        id: 2,
        title: 'Adidas Ultraboost',
        slug: 'adidas-ultraboost',
        heroImage: require('../assets/images/shoes2.png'),
        imagesUrl: [
          require('../assets/images/shoes2.png'),
          require('../assets/images/shoes1.png'),
        ],
        price: 179.99,
        category: {
          imageUrl: require('../assets/images/shoes2.png'),
          name: 'Adidas',
          slug: 'adidas',
        },
        gender: 'Men',
        sizes: [8, 9, 10, 11, 12],
        maxQuantity: 7,
      },
    ],
  },
  {
    id: '2',
    item: 'Order 2',
    details: 'Details about order 2',
    status: 'Completed',
    slug: 'order-2',
    date: '2024-07-02',
    items: [
      {
        id: 1,
        title: 'Nike Air Max 2024',
        slug: 'nike-air-max-2024',
        heroImage: require('../assets/images/shoes1.png'),
        imagesUrl: [
          require('../assets/images/shoes1.png'),
          require('../assets/images/shoes2.png'),
          require('../assets/images/shoes3.png'),
        ],
        price: 199.99,
        category: {
          imageUrl: require('../assets/images/shoes1.png'),
          name: 'Nike',
          slug: 'nike',
        },
        gender: 'Unisex',
        sizes: [7, 8, 9, 10, 11],
        maxQuantity: 5,
      },
      {
        id: 2,
        title: 'Adidas Ultraboost',
        slug: 'adidas-ultraboost',
        heroImage: require('../assets/images/shoes2.png'),
        imagesUrl: [
          require('../assets/images/shoes2.png'),
          require('../assets/images/shoes1.png'),
        ],
        price: 179.99,
        category: {
          imageUrl: require('../assets/images/shoes2.png'),
          name: 'Adidas',
          slug: 'adidas',
        },
        gender: 'Men',
        sizes: [8, 9, 10, 11, 12],
        maxQuantity: 7,
      },
    ],
  },
  {
    id: '3',
    item: 'Order 3',
    details: 'Details about order 3',
    status: 'Shipped',
    slug: 'order-3',
    date: '2024-07-03',
    items: [
      {
        id: 1,
        title: 'Nike Air Max 2024',
        slug: 'nike-air-max-2024',
        heroImage: require('../assets/images/shoes1.png'),
        imagesUrl: [
          require('../assets/images/shoes1.png'),
          require('../assets/images/shoes2.png'),
          require('../assets/images/shoes3.png'),
        ],
        price: 199.99,
        category: {
          imageUrl: require('../assets/images/shoes1.png'),
          name: 'Nike',
          slug: 'nike',
        },
        gender: 'Unisex',
        sizes: [7, 8, 9, 10, 11],
        maxQuantity: 5,
      },
      {
        id: 2,
        title: 'Adidas Ultraboost',
        slug: 'adidas-ultraboost',
        heroImage: require('../assets/images/shoes2.png'),
        imagesUrl: [
          require('../assets/images/shoes2.png'),
          require('../assets/images/shoes1.png'),
        ],
        price: 179.99,
        category: {
          imageUrl: require('../assets/images/shoes2.png'),
          name: 'Adidas',
          slug: 'adidas',
        },
        gender: 'Men',
        sizes: [8, 9, 10, 11, 12],
        maxQuantity: 7,
      },
    ],
  },
  {
    id: '4',
    item: 'Order 4',
    details: 'Details about order 4',
    status: 'InTransit',
    slug: 'order-4',
    date: '2024-07-04',
    items: [
      {
        id: 1,
        title: 'Nike Air Max 2024',
        slug: 'nike-air-max-2024',
        heroImage: require('../assets/images/shoes1.png'),
        imagesUrl: [
          require('../assets/images/shoes1.png'),
          require('../assets/images/shoes2.png'),
          require('../assets/images/shoes3.png'),
        ],
        price: 199.99,
        category: {
          imageUrl: require('../assets/images/shoes1.png'),
          name: 'Nike',
          slug: 'nike',
        },
        gender: 'Unisex',
        sizes: [7, 8, 9, 10, 11],
        maxQuantity: 5,
      },
      {
        id: 2,
        title: 'Adidas Ultraboost',
        slug: 'adidas-ultraboost',
        heroImage: require('../assets/images/shoes2.png'),
        imagesUrl: [
          require('../assets/images/shoes2.png'),
          require('../assets/images/shoes1.png'),
        ],
        price: 179.99,
        category: {
          imageUrl: require('../assets/images/shoes2.png'),
          name: 'Adidas',
          slug: 'adidas',
        },
        gender: 'Men',
        sizes: [8, 9, 10, 11, 12],
        maxQuantity: 7,
      },
    ],
  },
];
