import { Product } from './types/product';


export const PRODUCTS: Product[] = [
  {
    id: 1,
    title: 'Nike Air Max 2024',
    slug: 'nike-air-max-2024',
    heroImage: require('../assets/images/shoes1.png'),
    imagesUrl: [
      require('../assets/images/shoes1.png'),
      require('../assets/images/shoes2.png'),
      require('../assets/images/shoes3.png'),
    ],
    price: 199.99,
    category: {
      imageUrl: require('../assets/images/shoes1.png'),
      name: 'Nike',
      slug: 'nike',
    },
    gender: 'Unisex',
    sizes: [7, 8, 9, 10, 11],
    maxQuantity: 5,
  },
  {
    id: 2,
    title: 'Adidas Ultraboost',
    slug: 'adidas-ultraboost',
    heroImage: require('../assets/images/shoes2.png'),
    imagesUrl: [
      require('../assets/images/shoes2.png'),
      require('../assets/images/shoes1.png'),
    ],
    price: 179.99,
    category: {
      imageUrl: require('../assets/images/shoes2.png'),
      name: 'Adidas',
      slug: 'adidas',
    },
    gender: 'Men',
    sizes: [8, 9, 10, 11, 12],
    maxQuantity: 7,
  },
  {
    id: 3,
    title: 'Puma RS-X',
    slug: 'puma-rs-x',
    heroImage: require('../assets/images/shoes3.png'),
    imagesUrl: [
      require('../assets/images/shoes1.png'),
      require('../assets/images/shoes2.png'),
    ],
    price: 159.99,
    category: {
      imageUrl: require('../assets/images/shoes3.png'),
      name: 'Puma',
      slug: 'puma',
    },
    gender: 'Women',
    sizes: [6, 7, 8, 9, 10],
    maxQuantity: 10,
  },
  {
    id: 4,
    title: 'Reebok Nano X2',
    slug: 'reebok-nano-x2',
    heroImage: require('../assets/images/shoes2.png'),
    imagesUrl: [
      require('../assets/images/shoes4.png'),
      require('../assets/images/shoes3.png'),
    ],
    price: 129.99,
    category: {
      imageUrl: require('../assets/images/shoes4.png'),
      name: 'Reebok',
      slug: 'reebok',
    },
    gender: 'Unisex',
    sizes: [7, 8, 9, 10, 11],
    maxQuantity: 12,
  },
  {
    id: 5,
    title: 'New Balance 574',
    slug: 'new-balance-574',
    heroImage: require('../assets/images/shoes1.png'),
    imagesUrl: [
      require('../assets/images/shoes1.png'),
      require('../assets/images/shoes1.png'),
    ],
    price: 149.99,
    category: {
      imageUrl: require('../assets/images/shoes1.png'),
      name: 'New Balance',
      slug: 'new-balance',
    },
    gender: 'Men',
    sizes: [8, 9, 10, 11, 12],
    maxQuantity: 8,
  },
  {
    id: 6,
    title: 'Asics Gel-Kayano',
    slug: 'asics-gel-kayano',
    heroImage: require('../assets/images/shoes1.png'),
    imagesUrl: [
      require('../assets/images/shoes1.png'),
      require('../assets/images/shoes1.png'),
    ],
    price: 139.99,
    category: {
      imageUrl: require('../assets/images/shoes1.png'),
      name: 'Asics',
      slug: 'asics',
    },
    gender: 'Women',
    sizes: [6, 7, 8, 9, 10],
    maxQuantity: 6,
  },
  {
    id: 7,
    title: 'Vans Old Skool',
    slug: 'vans-old-skool',
    heroImage: require('../assets/images/shoes1.png'),
    imagesUrl: [
      require('../assets/images/shoes1.png'),
      require('../assets/images/shoes1.png'),
    ],
    price: 99.99,
    category: {
      imageUrl: require('../assets/images/shoes1.png'),
      name: 'Vans',
      slug: 'vans',
    },
    gender: 'Unisex',
    sizes: [5, 6, 7, 8, 9, 10],
    maxQuantity: 10,
  },
  {
    id: 8,
    title: 'Under Armour HOVR',
    slug: 'under-armour-hovr',
    heroImage: require('../assets/images/shoes1.png'),
    imagesUrl: [
      require('../assets/images/shoes1.png'),
      require('../assets/images/shoes1.png'),
    ],
    price: 99.99,
    category: {
      imageUrl: require('../assets/images/shoes1.png'),
      name: 'Under Armour',
      slug: 'under-armour',
    },
    gender: 'Unisex',
    sizes: [5, 6, 7, 8, 9, 10],
    maxQuantity: 10,
  },
];
